---
server:
    install: '1'
    packages: [npm, git, vim, nodejs]
    timezone: America/Recife
    locale: pt_BR.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty32, hostname: phpeste, ip: 192.168.33.99, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: rsync }
nginx:
    install: '1'
    docroot: /vagrant
    servername: myApp.vb
mongodb:
    install: '1'
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php-pear, php5-xdebug, php5-mysql, php5-mongo, php5-curl]
composer:
    install: '1'

