language: php

php:
  - 5.6
  - '7'

matrix:
  allow_failures:
    - php: '7'
    
services: mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer selfupdate
  - composer install --no-interaction --prefer-dist --no-scripts

  - app/console doctrine:mongodb:fixtures:load
  
notifications:
  email: false
  
script: 
  - ./bin/phpunit -c app
  - ./bin/behat
