language: php

php:
  - 5.6
  - '7'

matrix:
  allow_failures:
    - php: '7'

env:
  global:
    - MONGO_HOST=127.0.0.1
    - BASE_URL=127.0.0.1

services: mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer selfupdate
  - composer install --no-interaction --prefer-dist --no-scripts

  - chmod -R 777 app/cache app/logs
  - app/console --env=test cache:warmup
  - chmod -R 777 app/cache app/logs

#  - app/console doctrine:mongodb:fixtures:load

  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  - sleep 5

notifications:
  email: false
  
script: 
  - ./bin/phpunit -c app
  - ./bin/behat
