language: php

env:
  global:
    - MONGO_HOST=127.0.0.1
    - BASE_URL=127.0.0.1:8080

php:
  - 7.1

matrix:
  allow_failures:
    - php: 7.1

notifications:
  email: false

script: 
  - ./bin/phpunit -c app
  - ./bin/docheader check src/
  - ./bin/behat
