language: php

env:
  global:
    - MONGO_HOST=127.0.0.1
    - BASE_URL=localhost

php:
  - 5.6
  - 7

matrix:
  allow_failures:
    - php: 7

services: mongodb

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi

  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  - composer selfupdate
  - composer install --no-interaction --prefer-dist --no-scripts

  - chmod -R 777 app/cache app/logs
  - app/console --env=test cache:warmup
  - chmod -R 777 app/cache app/logs

  - app/console doctrine:mongodb:schema:create
  - app/console doctrine:mongodb:fixtures:load

  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  - sleep 5

notifications:
  email: false

script: 
  - ./bin/phpunit -c app
  - ./bin/behat
