language: php

env:
  global:
    - MONGO_HOST=127.0.0.1
    - BASE_URL=localhost:8080

php:
  - 5.6
  - 7

matrix:
  allow_failures:
    - php: 7

services: mongodb

addons:
  apt:
    packages:
      - nginx

before_script:
  - sudo apt-get install -y nginx
  - sudo apt-get install -y php5-fpm php5-curl php5-sqlite
  - sudo cp .travis.nginx.conf /etc/nginx/nginx.conf
  - sudo service nginx restart

  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer selfupdate
  - composer install --no-interaction --prefer-dist --no-scripts

  - chmod -R 777 app/cache app/logs
  - app/console --env=test cache:warmup
  - chmod -R 777 app/cache app/logs

  - app/console doctrine:mongodb:schema:create
  - app/console doctrine:mongodb:fixtures:load

  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  - sleep 5

notifications:
  email: false

script: 
  - ./bin/phpunit -c app
  - ./bin/behat
